### ISSUE TITLE
Kickstart for Debian

### ISSUE THREAD

**Issue by servancho** [servancho/pytin#9]
Need script that installs Debian on KVM automatically.

**Comment by RemiZOffAlex** [comment]
cmd = 'qm create ' + VMID + ''' --args "-append 'install auto=true priority=critical preseed/url=http://server.pxe/''' + KICKSTART_FILE_NAME
    cmd += '''' -kernel '''
    cmd += WORKDIR + '/linux -initrd ' + WORKDIR + '/initrd.gz" --ide2 local:iso/faiboot.iso,media=cdrom'
    cmd += ' --name ' + VMNAME + ' --net0 rtl8139,rate=50,bridge=vmbr0 --virtio0 local:' + HDDGB
    cmd += ',format=qcow2,cache=writeback,mbps_rd=5,mbps_wr=5 --bootdisk virtio0 --ostype l26 --memory '
    cmd += MEMMB + ' --onboot yes --cores ' + VCPU + ' --sockets 1'

**Comment by RemiZOffAlex** [comment]
https://github.com/servancho/pytin/blob/master/scripts/debian/fai/virt/kvm/debian.7.fai.tpl

**Comment by RemiZOffAlex** [comment]
#!ipxe

echo {{ uuid }}
set urlmirror http://mirror.yandex.ru/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64
echo Load kernel...
kernel ${urlmirror}/linux auto url=http://server.pxe/debian.auto.php
echo Load initrd...
initrd ${urlmirror}/initrd.gz
echo Boot
boot

**Comment by RemiZOffAlex** [comment]
https://github.com/RemiZOffAlex/pytin-agent
